image: registry.tech4comp.dbis.rwth-aachen.de/rwthacis/latex:master

stages:
  - build
  - lint

.build-tex:
  variables: 
    TEX_CMD: "latexmk -xelatex -latexoption='-shell-escape'"
  artifacts:
    paths:
      - ${TEX_DIR}/${TEX_JOB}.pdf
      - ${TEX_DIR}/${TEX_JOB}.aux
    expire_in: 5 m
  script:
    - cd "${TEX_DIR}" && ${TEX_CMD} "${TEX_JOB}.tex"

build-thesis-text:
  stage: build
  variables: 
    TEX_DIR: 'thesis/text'
    TEX_JOB: 'thesis'
  extends: .build-tex
    
build-thesis-slides:
  stage: build
  variables: 
    TEX_DIR: 'thesis/presentation'
    TEX_JOB: 'thesis-slides'
  extends: .build-tex

build-proposal-text:
  stage: build
  variables: 
    TEX_DIR: 'proposal/text'
    TEX_JOB: 'proposal'
  extends: .build-tex
    
build-proposal-slides:
  stage: build
  variables: 
    TEX_DIR: 'proposal/presentation'
    TEX_JOB: 'proposal-slides'
  extends: .build-tex

lint-proposal-job:   
  stage: lint    
  dependencies:
    - build-proposal-text
  artifacts:
    paths:
      - proposal/text/chktex.txt
      - proposal/text/chktex.svg
    expire_in: 5 m
  script:
    - cd proposal/text && chktex -v1 -o chktex.txt proposal.tex || true
    - c=($(grep -c "Warning" chktex.txt))|| true && c="${c:-0}" && if [[ $c -gt 10 ]]; then anybadge -l $c -v "TeX Warnings" -f chktex.svg -c red; else if [[ $c -gt 0 ]]; then anybadge -l $c -v "TeX Warnings" -f chktex.svg -c orange; else anybadge -l "0" -v "TeX Warnings" -f chktex.svg -c green; fi; fi

lint-thesis-job:   
  stage: lint    
  dependencies:
    - build-thesis-text
  artifacts:
    paths:
      - thesis/text/chktex.txt
      - thesis/text/chktex.svg
    expire_in: 5 m
  script:
    - cd thesis/text && chktex -v1 -o chktex.txt thesis.tex || true
    - c=($(grep -c "Warning" chktex.txt))|| true && c="${c:-0}" && if [[ $c -gt 10 ]]; then anybadge -l $c -v "TeX Warnings" -f chktex.svg -c red; else if [[ $c -gt 0 ]]; then anybadge -l $c -v "TeX Warnings" -f chktex.svg -c orange; else anybadge -l "0" -v "TeX Warnings" -f chktex.svg -c green; fi; fi

lint-readability-proposal:   
  stage: lint    
  dependencies:
    - build-proposal-text
  artifacts:
    paths:
      - proposal/text/readability.svg
      - proposal/text/bib.svg
      - proposal/text/bib.html
    expire_in: 5 m
  script:
    - cd proposal/text && pandoc --from latex --to plain -o proposal.txt proposal.tex || true
    - c=($(python3 ../../tools/text-stat.py -t proposal.txt))|| true && c="${c:-0}" && if [[ $c -gt 89 ]]; then anybadge -l $c -v "Very Easy" -f readability.svg -c green; else if [[ $c -gt 79 ]]; then anybadge -l $c -v "Easy" -f readability.svg -c green; else if [[ $c -gt 69 ]]; then anybadge -l $c -v "Fairly Easy" -f readability.svg -c green; else if [[ $c -gt 59 ]]; then anybadge -l $c -v "Standard" -f readability.svg -c orange; else if [[ $c -gt 49 ]]; then anybadge -l $c -v "Fairly Difficult" -f readability.svg -c orange; else if [[ $c -gt 29 ]]; then anybadge -l $c -v "Difficult" -f readability.svg -c red; else anybadge -l $c -v "Very Confusing" -f readability.svg -c red; fi; fi; fi; fi; fi; fi
    - c=($(python3 ../../tools/biblatex_check.py -b ../../bibliography/bibliography.bib -a proposal.aux -o bib.html))  && c="${c:-0}" && if [[ $c -gt 10 ]]; then anybadge -l $c -v "Reference Warnings" -f bib.svg -c red; else if [[ $c -gt 0 ]]; then anybadge -l $c -v "Reference Warnings" -f bib.svg -c orange; else anybadge -l "0" -v "Reference Warnings" -f bib.svg -c green; fi; fi

lint-readability-thesis:   
  stage: lint    
  dependencies:
    - build-thesis-text
  artifacts:
    paths:
      - thesis/text/readability.svg
      - thesis/text/bib.svg
      - thesis/text/bib.html
    expire_in: 5 m
  script:
    - cd thesis/text && pandoc --from latex --to plain -o thesis.txt thesis.tex || true
    - c=($(python3 ../../tools/text-stat.py -t thesis.txt))|| true && c="${c:-0}" && if [[ $c -gt 89 ]]; then anybadge -l $c -v "Very Easy" -f readability.svg -c green; else if [[ $c -gt 79 ]]; then anybadge -l $c -v "Easy" -f readability.svg -c green; else if [[ $c -gt 69 ]]; then anybadge -l $c -v "Fairly Easy" -f readability.svg -c green; else if [[ $c -gt 59 ]]; then anybadge -l $c -v "Standard" -f readability.svg -c orange; else if [[ $c -gt 49 ]]; then anybadge -l $c -v "Fairly Difficult" -f readability.svg -c orange; else if [[ $c -gt 29 ]]; then anybadge -l $c -v "Difficult" -f readability.svg -c red; else anybadge -l $c -v "Very Confusing" -f readability.svg -c red; fi; fi; fi; fi; fi; fi
    - c=($(python3 ../../tools/biblatex_check.py -b ../../bibliography/bibliography.bib -a thesis.aux -o bib.html))  && c="${c:-0}" && if [[ $c -gt 10 ]]; then anybadge -l $c -v "Reference Warnings" -f bib.svg -c red; else if [[ $c -gt 0 ]]; then anybadge -l $c -v "Reference Warnings" -f bib.svg -c orange; else anybadge -l "0" -v "Reference Warnings" -f bib.svg -c green; fi; fi

lint-spell-proposal:   
  stage: lint    
  dependencies:
    - build-proposal-text
  artifacts:
    paths:
      - proposal/text/cspell.txt
      - proposal/text/cspell.svg
    expire_in: 5 m
  script:
    - npx cspell lint -c .vscode/cspell.json proposal/text/*.tex proposal/text/*/*.tex > proposal/text/cspell.txt || true
    - cd proposal/text && c=($(wc -l cspell.txt))|| true && c="${c:-0}" && if [[ $c -gt 10 ]]; then anybadge -l $c -v "Spelling Mistakes" -f cspell.svg -c red; else if [[ $c -gt 0 ]]; then anybadge -l $c -v "Spelling Mistakes" -f cspell.svg -c orange; else anybadge -l "0" -v "Spelling Mistakes" -f cspell.svg -c green; fi; fi

lint-spell-thesis:   
  stage: lint    
  dependencies:
    - build-thesis-text
  artifacts:
    paths:
      - thesis/text/cspell.txt
      - thesis/text/cspell.svg
    expire_in: 5 m
  script:
    - npx cspell lint -c .vscode/cspell.json thesis/text/*.tex thesis/text/*/*.tex > thesis/text/cspell.txt || true
    - cd thesis/text && c=($(wc -l cspell.txt))|| true && c="${c:-0}" && if [[ $c -gt 10 ]]; then anybadge -l $c -v "Spelling Mistakes" -f cspell.svg -c red; else if [[ $c -gt 0 ]]; then anybadge -l $c -v "Spelling Mistakes" -f cspell.svg -c orange; else anybadge -l "0" -v "Spelling Mistakes" -f cspell.svg -c green; fi; fi
